import {
  SiTypescript,
  SiMongodb,
  SiNextdotjs,
  SiReact,
  SiNodedotjs,
  SiTailwindcss,
  SiFirebase,
  SiRedux,
  SiPostgresql,
  SiPython,
  SiJavascript,
  SiExpress,
  SiVercel,
  SiBetterauth,
  SiJsonwebtokens,
  SiNetlify,
  SiFramer,
  SiFigma,
  SiDocker,
  SiRailway,
  SiSocketdotio,
  SiSwagger,
  SiShadcnui,
  SiRedis,
} from "react-icons/si";
import { FaCcStripe, FaGitAlt, FaStripe } from "react-icons/fa";

export const techIconMap = {
  TypeScript: SiTypescript,
  MongoDB: SiMongodb,
  "Next.js": SiNextdotjs,
  React: SiReact,
  "Node.js": SiNodedotjs,
  Tailwind: SiTailwindcss,
  "Tailwind CSS": SiTailwindcss,
  Firebase: SiFirebase,
  Redux: SiRedux,
  "Redux Toolkit": SiRedux,
  PostgreSQL: SiPostgresql,
  Python: SiPython,
  JavaScript: SiJavascript,
  Express: SiExpress,
  Razorpay: FaCcStripe,
  Git: FaGitAlt,
  "shadcn/ui": SiShadcnui,
  Cloudinary: SiSwagger,
  Recharts: SiReact,
  JWT: SiJsonwebtokens,
  Vercel: SiVercel,
  BetterAuth: SiBetterauth,
  "Better Auth": SiBetterauth,
  Netlify: SiNetlify,
  Stripe: FaStripe,
  "Framer Motion": SiFramer,
  Figma: SiFigma,
  Docker: SiDocker,
  Railway: SiRailway,
  "Socket.io": SiSocketdotio,
  "REST API": SiSwagger,
  Redis: SiRedis,
};

export const getTechIcon = (techName) => {
  return techIconMap[techName] || SiReact;
};
